# ruff: noqa: F401
# app/ui_helpers.py — Facade exposing all dashboard presentation helpers.

from app.ui_helpers_format import (
    EXECUTIVE_METRICS,
    QUALITY_SCORE_COLUMNS,
    QUALITY_STATUS_ORDER,
    DECISION_BRIEF_IMPACT_COLUMNS,
    DECISION_BRIEF_IMPACT_LABELS,
    DECISION_BRIEF_TITLE_COLUMNS,
    DECISION_BRIEF_ACTION_COLUMNS,
    DECISION_BRIEF_OWNER_COLUMNS,
    DECISION_BRIEF_STATUS_COLUMNS,
    DECISION_BRIEF_SORT_COLUMNS,
    CUSTOMER_QUEUE_COLUMNS,
    CUSTOMER_RISK_ORDER,
    ACTION_QUEUE_COLUMNS,
    ACTION_EFFORT_ORDER,
    QUICK_VIEW_OPTIONS,
    QUICK_VIEW_DESCRIPTIONS,
    SCENARIO_ANALYSIS_COLUMNS,
    format_currency,
    format_percentage,
    format_number,
    safe_metric_value,
    select_metric_value,
    status_badge_text,
    format_file_size,
    format_timestamp,
    format_duration,
    build_data_freshness_summary,
    build_demo_readiness_summary,
    db_status_label,
    safe_dataframe_empty_message,
    prepare_display_dataframe,
    dataframe_to_csv_bytes,
    build_export_filename,
)

from app.ui_helpers_filter import (
    get_filter_options,
    filter_dataframe_by_values,
    filter_dataframe_by_search,
    filter_dataframe_by_numeric_range,
    get_quick_view_options,
    describe_quick_view,
    apply_quick_view,
    prepare_metric_chart_data,
    prepare_status_counts,
    prepare_category_counts,
    get_executive_metric_values,
)

from app.ui_helpers_actions import (
    prepare_top_actions,
    build_top_actions_overview,
    prepare_action_priority_queue,
    build_decision_brief,
    decision_brief_to_markdown,
    prepare_owner_workload_summary,
)

from app.ui_helpers_customer import (
    build_custom_scenario_analysis,
    determine_business_status,
    quality_status_for_score,
    build_data_quality_overview,
    prepare_quality_dimension_summary,
    prepare_quality_issue_queue,
    filter_customer_360,
    build_customer_360_overview,
    prepare_customer_360_queue,
    build_customer_profile_summary,
    summarize_filter_state,
)
