"""
cashflow.py — Cash flow metric calculations.

All functions are pure, deterministic, and safe for zero denominators.
Inputs are plain floats; no DataFrames or side effects.

Covers:
- Operating cash flow
- Free cash flow
- Burn rate
- Runway
- Cash conversion cycle
"""

from __future__ import annotations

from core.business_health._utils import safe_divide


def calculate_operating_cash_flow(
    net_income: float,
    non_cash_expenses: float,
    working_capital_change: float,
) -> float:
    """
    Operating Cash Flow = Net Income + Non-Cash Expenses - Working Capital Change.

    Approximates cash generated by operations by adding back non-cash
    charges and adjusting for changes in working capital.

    A positive working_capital_change means working capital increased
    (cash consumed). Pass increases as positive, decreases as negative.
    """
    return net_income + non_cash_expenses - working_capital_change


def calculate_free_cash_flow(
    operating_cash_flow: float, capital_expenditures: float
) -> float:
    """
    Free Cash Flow = Operating Cash Flow - Capital Expenditures.

    Cash available after sustaining and expanding the asset base.
    Negative FCF is common in high-growth companies reinvesting heavily.
    """
    return operating_cash_flow - capital_expenditures


def calculate_burn_rate(
    monthly_cash_outflow: float, monthly_cash_inflow: float
) -> float:
    """
    Burn Rate = Monthly Cash Outflow - Monthly Cash Inflow.

    Net cash consumed per month. Positive burn means more spent than earned.
    Negative burn means the company is cash-flow positive.
    """
    return monthly_cash_outflow - monthly_cash_inflow


def calculate_runway(cash_balance: float, monthly_burn_rate: float) -> float:
    """
    Runway = Cash Balance / Monthly Burn Rate.

    Number of months the business can operate at current burn before cash runs out.
    Returns 0.0 when burn rate is zero or negative (company is profitable or not burning).

    Note: meaningful only when monthly_burn_rate > 0.
    """
    if monthly_burn_rate <= 0:
        return 0.0
    return safe_divide(cash_balance, monthly_burn_rate)


def calculate_cash_conversion_cycle(
    days_inventory_outstanding: float,
    days_sales_outstanding: float,
    days_payables_outstanding: float,
) -> float:
    """
    CCC = DIO + DSO - DPO.

    Cash Conversion Cycle — number of days cash is tied up in operations.
    Lower CCC means the business converts inventory/receivables to cash faster.
    Negative CCC is possible when payables terms are longer than receivables collection.
    """
    return days_inventory_outstanding + days_sales_outstanding - days_payables_outstanding
